[default]
ident = "Smart Pegon"
address = "0.0.0.0"
port = 8000
keep_alive = 120
template_dir = "views"
temp_dir = "images/temp"

[default.limits]
file = "30 MiB"
data-form = "33 MiB"

[release]
log_level = "critical"
