//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::image_transliterations::Entity as ImageTransliterations;
pub use super::text_transliterations::Entity as TextTransliterations;
pub use super::users::Entity as Users;
