//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::Gender;
use super::sea_orm_active_enums::Status;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Binary(16)")]
    pub id: Vec<u8>,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(unique)]
    pub photo_profile: Option<String>,
    pub full_name: String,
    pub gender: Gender,
    pub date_of_birth: Date,
    pub status: Status,
    pub learning_level: i32,
    pub learning_stage_level: i32,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub expired_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::image_transliterations::Entity")]
    ImageTransliterations,
    #[sea_orm(has_many = "super::text_transliterations::Entity")]
    TextTransliterations,
    #[sea_orm(has_many = "super::transactions::Entity")]
    Transactions,
}

impl Related<super::image_transliterations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImageTransliterations.def()
    }
}

impl Related<super::text_transliterations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TextTransliterations.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
