pub mod auth_controller;
pub mod check_controller;
pub mod home_controller;
pub mod image_transliteration_controller;
pub mod text_transliteration_controller;
pub mod transaction_controller;
pub mod translation_controller;
pub mod user_controller;
pub mod kajian_controller;
